### ISSUE TITLE
[Makefile:8: run]

### ISSUE THREAD

**Issue by lilkdi** [gp2112/bitcoin-vanity-gen#2]
make requirements -- success, but make run return:

```
go run qrcode.go vanity.go
vanity.go:9:2: no required module provides package github.com/btcsuite/btcutil/base58: go.mod file not found in current directory or any parent directory; see 'go help modules'
qrcode.go:9:2: no required module provides package github.com/fumiyas/go-tty: go.mod file not found in current directory or any parent directory; see 'go help modules'
qrcode.go:8:2: no required module provides package github.com/fumiyas/qrc/lib: go.mod file not found in current directory or any parent directory; see 'go help modules'
vanity.go:5:2: no required module provides package github.com/haltingstate/secp256k1-go: go.mod file not found in current directory or any parent directory; see 'go help modules'
qrcode.go:6:2: no required module provides package github.com/mattn/go-colorable: go.mod file not found in current directory or any parent directory; see 'go help modules'
qrcode.go:4:2: no required module provides package github.com/qpliu/qrencode-go/qrencode: go.mod file not found in current directory or any parent directory; see 'go help modules'
vanity.go:8:2: no required module provides package golang.org/x/crypto/ripemd160: go.mod file not found in current directory or any parent directory; see 'go help modules'
make: *** [Makefile:8: run]
```

**Comment by gp2112** [comment]
Hello lilkdi.
The issue is that you are trying to run on go v1.16, that requires to have go.mod file at the same directory.
This code was written in v13, in 2018, and I haven't worked with go so much since...

There are two solutions: 

1. Create a go.mod file:
  The problem with this solution is that some modules of qrcode.go are having conflicts with v1.16, so you should install only the requirements from vanity.go, leaving them on Makefile:

- golang.org/x/crypto
- github.com/btcsuite/btcutil/base58
- github.com/haltingstate/secp256k1-go 
   
   then:
   `$ go mod init btcvanity`
   `$ make requirements` [so they get added to go.mod]
   `$ go run vanity.go`

2. Change to go v13:
   Just `$ sudo apt-get install golang` 

If you choose the first option, feel free to make a branch and a pull request :)

gp2112
